version: '2'

services:
  coreconnect:
    build:
      context: .
      dockerfile: coreconnect/Dockerfile
    command: python coreconnect/manage.py runserver 0.0.0.0:8000
    ports:
      - 0.0.0.0:8000:8000
    volumes:
      - .:/code
  fetcher:
    build:
      context: .
      dockerfile: fetcher/Dockerfile
    command: npx pm2 start --no-daemon index.js
    ports:
      - 0.0.0.0:3000:3000